### ISSUE TITLE
导出后 '#'与标题连着 中间无空格 显示不正常

### ISSUE THREAD

**Issue by n4v1z** [pibigstar/csdn-hexo#1]
其他导出都正常
标题大部分都出问题

如导出格式为这样
```
#正则表达式
##什么是正则表达式？
```
需要都是间隔一个空格
```
# 正则表达式
## 什么是正则表达式？
```
如果富文本编辑器也能导出为MD格式最好拉

**Comment by pibigstar** [comment]
>没空格是因为当初你写的时候就没写空格吧，因为CSDN你写没空格，它也能识别，但是有些解析器可能识别不了，所以我写的时候都会多敲个空格的，你可以改源代码，利用正则，替换一下

```go
	str := `##正则表达式
		    ###什么是正则表达式？`
	r := regexp.MustCompile("#+")
	newStr := r.ReplaceAllStringFunc(str, func(s string) string {
		s = s + " "
		return s
	})
```

> 富文本需要进一步转化成Markdown格式，Go应该这方面的第三方类库，你可以研究一下，欢迎提PR

**Comment by pibigstar** [comment]
> 其他导出都正常
> 标题大部分都出问题
> 
> 如导出格式为这样
> 
> ```
> #正则表达式
> ##什么是正则表达式？
> ```
> 
> 需要都是间隔一个空格
> 
> ```
> # 正则表达式
> ## 什么是正则表达式？
> ```
> 
> 如果富文本编辑器也能导出为MD格式最好拉

**Comment by n4v1z** [comment]
并没有  好像CSDN上博客显示是正常，这个我回头用正则表达式修改下就行。

**Comment by pibigstar** [comment]
可以试试这个 https://github.com/TruthHun/html2md
