### ISSUE TITLE
失败了

### ISSUE THREAD

**Issue by Brannua** [pibigstar/csdn-hexo#2]

**Comment by Brannua** [comment]
二进制文件执行进度条为 0；源码方式终端卡住没有任何输出，求助

**Comment by pibigstar** [comment]
@Brannua 简单看了下，发现是CSDN把接口地址换了，并且做了加密，新接口地址：
https://bizapi.csdn.net/blog-console-api/v3/editor/getArticle?id=113813265&model_type=  
我明天有时间的话试试看能不能把他们加密算法给搞定吧。。。

**Comment by Brannua** [comment]
谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 晚上8:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pibigstar/csdn-hexo] 失败了 (#2)




 
@Brannua 简单看了下，发现是CSDN把接口地址换了，并且做了加密，新接口地址：
 https://bizapi.csdn.net/blog-console-api/v3/editor/getArticle?id=113813265&amp;model_type=
 我明天有时间的话试试看能不能把他们加密算法给搞定吧。。。

**Comment by pibigstar** [comment]
@Brannua 改好了，再试下吧

**Comment by Brannua** [comment]
感谢回复，经过测试，依然会卡住，请求结束后报网络请求超时，似乎无法访问proxy.golang.org ，当然只是猜测，试图添加hosts映射并刷新后没有解决，这个程序需要设置代理么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月18日(周四) 下午5:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pibigstar/csdn-hexo] 失败了 (#2)




 
@Brannua 改好了，再试下吧

**Comment by Brannua** [comment]
重启了下系统，成功了，感谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月18日(周四) 下午5:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pibigstar/csdn-hexo] 失败了 (#2)




 
@Brannua 改好了，再试下吧
